/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#5f5e5e',
        'on-primary': '#ffffff',
        'primary-container': '#adabab',
        'on-primary-container': '#40403f',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1b1b1b',
        'secondary': '#755b00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed977',
        'on-secondary-container': '#785d00',
        'secondary-fixed': '#ffe08f',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface': '#f9f9f9',
        'on-surface': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'on-surface-variant': '#4d4637',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'inverse-surface': '#2f3131',
        'outline': '#7e7665',
        'outline-variant': '#d0c5b2',
      },
      fontFamily: {
        headline: ['Newsreader', 'Georgia', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
